### ISSUE TITLE
Publish the MkDocs SVG rendering plugin as a PyPI package

### ISSUE THREAD

**Issue by aabounegm** [fizruk/rzk#54]
Currently, the [`generate_svgs.py`](https://github.com/fizruk/rzk/blob/914fcb67635b71999368e498611c511a26faf068/docs/generate_svgs.py) plugin is registered as a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks). To be able to reuse it with other projects that depend on rzk, it should be packaged as a proper [MkDocs plugin](https://www.mkdocs.org/dev-guide/plugins/) and published on PyPI so that others can install and use it.

Possible configuration options:
- Path to rzk binary (defaults to using PATH)

**Question**: Is it desirable to automatically install rzk (from GitHub releases) if not found?

**Comment by fizruk** [comment]
I think for the PyPI package by default you should assume that `rzk` is in `PATH`.
