### ISSUE TITLE
undefined variable: Eq

### ISSUE THREAD

**Issue by jonweinb** [fizruk/rzk#56]
With rzk v0.5, when trying to typecheck yoneda/src/simplicial-hott/04-extension-types.rzk.md, I'm getting:

```
src/simplicial-hott/04-extension-types.rzk.md:
  Error occurred when checking
    #define flip-ext-fun

undefined variable: Eq
```

I get the same error when permuting the definitions, e.g. putting curry-uncurry before.

**Comment by fizruk** [comment]
Can you point to the specific version of the code (commit hash) in the emilyriehl/yoneda repository? And also the full command that you run? I cannot reproduce locally.

**Comment by jonweinb** [comment]
I am also working with [emilyriehl/yoneda@6524ffd](https://github.com/emilyriehl/yoneda/commit/6524ffd97fbe99068572c94fa0006d0f5af3fcc7).

I am using rzk in the latest version of the development branch.

The command is:
`rzk typecheck src/simplicial-hott/* src/hott/*`

The full result is:
`Loading file src/simplicial-hott/03-simplicial-type-theory.rzk.md
Loading file src/simplicial-hott/04-extension-types.rzk.md
Loading file src/simplicial-hott/05-segal-types.rzk.md
Loading file src/simplicial-hott/06-2cat-of-segal-types.rzk.md
Loading file src/simplicial-hott/07-discrete.rzk.md
Loading file src/simplicial-hott/08-covariant.rzk.md
Loading file src/simplicial-hott/09-yoneda.rzk.md
Loading file src/simplicial-hott/10-rezk-types.rzk.md
Loading file src/simplicial-hott/12-cocartesian.rzk.md
Loading file src/hott/00-common.rzk.md
Loading file src/hott/01-paths.rzk.md
Loading file src/hott/02-homotopies.rzk.md
Loading file src/hott/03-equivalences.rzk.md
Loading file src/hott/04-sigma.rzk.md
Loading file src/hott/05-contractible.rzk.md
Loading file src/hott/06-fibers.rzk.md
Loading file src/hott/07-trivial-fibrations.rzk.md
Checking module from src/simplicial-hott/03-simplicial-type-theory.rzk.md
[ 1 out of 14 ] Checking #define Δ¹
[ 2 out of 14 ] Checking #define Δ²
[ 3 out of 14 ] Checking #define Δ³
[ 4 out of 14 ] Checking #define ∂Δ¹
[ 5 out of 14 ] Checking #define ∂Δ²
[ 6 out of 14 ] Checking #define Λ
[ 7 out of 14 ] Checking #define shapeProd
[ 8 out of 14 ] Checking #define Δ¹×Δ¹
[ 9 out of 14 ] Checking #define ∂□
[ 10 out of 14 ] Checking #define ∂Δ¹×Δ¹
[ 11 out of 14 ] Checking #define Δ¹×∂Δ¹
[ 12 out of 14 ] Checking #define Δ²×Δ¹
[ 13 out of 14 ] Checking #define shapeIntersection
[ 14 out of 14 ] Checking #define shapeUnion
Checking module from src/simplicial-hott/04-extension-types.rzk.md
[ 1 out of 14 ] Checking #define flip-ext-fun
An error occurred when typechecking!
Type Error:
Definitions in context:
Δ¹ : { x₁ : 2 } -> TOPE
Δ² : { x₁ : 2 * 2 } -> TOPE
Δ³ : { x₁ : 2 * 2 * 2 } -> TOPE
∂Δ¹ : { (x₁ : 2) | Δ¹ x₁ } -> TOPE
∂Δ² : { (x₁ : 2 * 2) | Δ² x₁ } -> TOPE
Λ : { x₁ : 2 * 2 } -> TOPE
shapeProd : { I : CUBE } -> { J : CUBE } -> { ψ : { x₁ : I } -> TOPE } -> { χ : { x₁ : J } -> TOPE } -> { x₁ : I * J } -> TOPE
Δ¹×Δ¹ : { x₁ : 2 * 2 } -> TOPE
∂□ : { x₁ : 2 * 2 } -> TOPE
∂Δ¹×Δ¹ : { x₁ : 2 * 2 } -> TOPE
Δ¹×∂Δ¹ : { x₁ : 2 * 2 } -> TOPE
Δ²×Δ¹ : { x₁ : 2 * 2 * 2 } -> TOPE
shapeIntersection : { I : CUBE } -> { ψ : { x₁ : I } -> TOPE } -> { χ : { x₁ : I } -> TOPE } -> { x₁ : I } -> TOPE
shapeUnion : { I : CUBE } -> { ψ : { x₁ : I } -> TOPE } -> { χ : { x₁ : I } -> TOPE } -> { x₁ : I } -> TOPE
I : CUBE
ψ : { x₁ : I } -> TOPE
ϕ : { (x₁ : I) | ψ x₁ } -> TOPE
X : U
Y : { (x₁ : I) | ψ x₁ } -> { x₂ : X } -> U
f : { (t : I) | ϕ t } -> { x : X } -> Y t x

when typechecking
  { I : CUBE } -> { ψ : { x₁ : I } -> TOPE } -> { ϕ : { x₁ : ψ } -> TOPE } -> { X : U } -> { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])
against type
  U

when inferring type for term
  { I : CUBE } -> { ψ : { x₁ : I } -> TOPE } -> { ϕ : { x₁ : ψ } -> TOPE } -> { X : U } -> { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  { ψ : { x₁ : I } -> TOPE } -> { ϕ : { x₁ : ψ } -> TOPE } -> { X : U } -> { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  { ϕ : { x₁ : ψ } -> TOPE } -> { X : U } -> { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  { X : U } -> { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  { Y : { x₁ : ψ } -> { x₂ : X } -> U } -> { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  { f : { t : ϕ } -> { x : X } -> Y t x } -> Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t]) ({ x : X } -> { (t : I) | ψ t } -> Y t x [ϕ t |-> f t x])

when inferring type for term
  Eq ({ (t : I) | ψ t } -> ({ x : X } -> Y t x) [ϕ t |-> f t])

Local tope context:
  TOP

src/simplicial-hott/04-extension-types.rzk.md:
  Error occurred when checking
    #define flip-ext-fun

undefined variable: Eq`

**Comment by jonweinb** [comment]
Ah, I realized my mistake just now calling the files in the wrong order. So sorry for bothering!
