### ISSUE TITLE
Error parsing code blocks with attributes

### ISSUE THREAD

**Issue by fredrik-bakke** [fizruk/rzk#63]
It seems that the `rzk` type checker does not know how to handle code blocks with attributes in markdown.

For instance, the following code is completely ignored:

````md
```rzk title="Rijke 22, Definition 9.3.1"
#def Eq-Σ
  ( s t : Σ (a : A) , B a)
  : U
  :=
    Σ ( p : (first s) = (first t)) ,
      ( transport A B (first s) (first t) p (second s)) = (second t)
```
````

The same happens if the attributes are wrapped in curly braces.

When I have two code blocks with attributes back to back, however, I get the following error:

```txt
An error occurred when parsing file src/hott/05-sigma.rzk.md
rzk: syntax error at end of file
CallStack (from HasCallStack):
  error, called at src/Rzk/Main.hs:67:9 in rzk-0.5.1-fd1942b5:Rzk.Main
```

**Comment by fizruk** [comment]
Thank you for reporting! I will make a minor release soon, which will include this fix!
